### ISSUE TITLE
Suggestion: Change title colour

### ISSUE THREAD

**Issue by Ishaq-A** [Ishaq-A/github-crash-course#1]
I think it would look better if the title was a bit more orange.

The styling rule could be changed like this:

```css
h1 {
    color: #e29b1f;
}
```
